# Generated by Django 4.0.6 on 2023-06-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_alter_categories_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
    ]
